### PR TITLE
Several improvements and features

### PR DESCRIPTION
**Pull request by Sanae6**
This pull cleans up a lot of the code, and adds some new functions/features. The cleaned up consists of removing unnecessary `this.VariableNameHere` accesses in a bunch of classes, unnecessary casts, and some unnecessary parentheses, and double comparison in LValue.

Anything that you don't want me to add can be removed, but the clean up removes certain practices mentioned in the first paragraph, so I'd suggest not removing them.

**Some of the code needs testing**, and I forgot to set the `room` built-in variable every step.

The main commit is 386f40c and it has a changelist you should definitely check out before this pull should be closed or continued.

### CODE REVIEW

**Comment by nommiin** [comment]
Thanks for the pull request! Unfortunately though, I don't think I'll be able to accept this as the removal of the various `this.` references in classes and `== true`/`== false` are just apart of my code style. If I were to accept, I'd still continue to write code this way and we'd be back at square one. I'll likely create a markdown file in the repository detailing the code style to follow. 

As for your additions to the code base, these are good additions. I should mention, runner-game related data would be stored in the "Game" class. Additionally, "room" is a built-in variable (not instance variable) as the value is pushed using the PushBuiltin instruction (which shouldn't access instance variables). I'll write an implementation for PushBuiltin with an example and push it shortly.

**Comment by Sanae6** [comment]
Alright, I'll respect your code style and won't bring it up again. It would be nice to have a code style file but it's definitely not top priority, and I can work it out from what you already have.

~~For "room", I'm a bit lost as for where to put it, there's no obvious location to implement the variable as a built-in.~~ Saw latest commit, just need to know where to put the very specific variables set by functions go. (see Function.draw_set_circle_precision in one of my recent commits) For the rest, I'm going to try and revert most of my commits, then re-implement them without modifying anything else.

**Comment by nommiin** [comment]
I appreciate the understanding.

As for where to store variables like that, I'd suggest storing runner-related functions in the `Game` class. I'd say it'd be best to store the circle precision variable under the `// Runner` comment or you can even make a new comment like `// Rendering` and store it there.

**Comment by Sanae6** [comment]
I'm closing this PR in favor of creating several different PRs for simplicity.

**Pull request closed without merging**
